#!/bin/bash

servers=$(cat server_count)
check(){

	if (( $1 == 1)); then
		log=$(heroku logs -a bullnexmc | grep "mem=" | tail -n1)
		name=$(heroku config:get SERVER_NAME -a bullnexmc)
	else
		log=$(heroku logs -a bullnexmc$i | grep "mem=" | tail -n1)
		name=$(heroku config:get SERVER_NAME -a bullnexmc$1)
	fi

	log=${log##*mem=}
	log=${log%)*}
	echo "($(cat .count))$i $name $log)" >> .data
	echo "$(($(cat .count) + 1))" > .count
}

echo "0" > .count
[ -f .data ] && rm .data
for i in {0..6}
do
	check $i &
done

while (($servers > $(cat .count)))
do
	sleep 1s
done

column -t -s ' ' .data
