#!/bin/bash

servers=$(cat server_count)
check(){

	i=$1
	if (( $i == 1)); then

		i=""
	fi

	log=$(heroku logs -a bullnexmc$i | grep "mem=" | tail -n1)
	log=${log##*mem=}
	log=${log%)*}
	echo "bullnexmc$i $log)" >> .data
	echo "$(($(cat .count) + 1))" > .count
}

echo "0" > .count
[[ -f .data ]] && rm .data
for i in {0..6}
do
	check $i &
done

while (($servers > $(cat .count)))
do
	sleep 1s
done

column -t -s ' ' .data
rm .data
