#!/bin/bash
check(){

	i=$1
	if (( $i == 1));
	then
		STATUS=$(heroku ps -a bullnexmc | grep "web.1")
	else
		STATUS=$(heroku config:get SERVER_NAME -a bullnexmc$i)$(heroku ps -a bullnexmc$i | grep "web.1")
	fi

	if [[ -z "$STATUS" ]]; then
		STATUS="Stopped"
	fi

	echo $i $STATUS
	echo "$(($(cat .count) + 1))" > .count
}


for i in {0..6}
do
	check $i &
done
echo "0" > .count
while (($(cat .count) < $(cat server_count)))
do
#	echo "$(cat .count)"
	sleep 1s
done
rm .count
