#!/bin/bash
check(){

	i=$1
	if (( $i == 1));
	then
		STATUS="$(heroku config:get SERVER_NAME -a bullnexmc) $(heroku ps -a bullnexmc | grep "web.1")"
	else
		STATUS="$(heroku config:get SERVER_NAME -a bullnexmc$i) $(heroku ps -a bullnexmc$i | grep "web.1")"
	fi

	echo "$i $STATUS" >> .data
	echo "$(($(cat .count) + 1))" > .count
}

[[ -f .data ]] && rm .data
for i in {0..6}
do
	check $i &
done
echo "0" > .count
while (($(cat .count) < $(cat server_count)))
do
#	echo "$(cat .count)"
	sleep 1s
done
rm .count

column -t -s ' ' .data
rm .data
